### ISSUE TITLE
OCP 4 OLM Mirroring and sample operator managed image sync script

### ISSUE THREAD

**Issue by aizuddin85** [redhat-cop/openshift-toolkit#119]
Lack of reliable scripts to do OLM content mirroring for OCP 4 restricted network installation. We should have one from redhat-cop.  This also can be extended to ocp 4 sample operator managed imagestream.

**Comment by garethahealy** [comment]
@aizuddin85 ; i know this has been talked about on the sme list. are you suggesting following what has been talked about there or something else?

**Comment by aizuddin85** [comment]
@garethahealy i might missed the sme list thread (tried to search sme list but cant find any probably bad keyword search). this is to ease OLM mirroring for restricted network installation. not sure if someone already work on it.

**Comment by aizuddin85** [comment]
> @garethahealy i might missed the sme list thread (tried to search sme list but cant find any probably bad keyword search). this is to ease OLM mirroring for restricted network installation. not sure if someone already work on it.

Found the thread and RFE: https://github.com/operator-framework/enhancements/blob/master/enhancements/opm-mirroring.md. Closing this issue.
