### ISSUE TITLE
Branding playbooks need to be grouped under a soluition.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-toolkit#30]
@Jooho could you update the two Branding playbooks to be under a directory called `branding`?

**Comment by Jooho** [comment]
This issue is solved @etsauer could you close it?

**Comment by etsauer** [comment]
@Jooho I would like to get you added to the Contributors team (sent you an invite) so that I can assign you to this issue and give you credit. #ninja-points!

**Comment by Jooho** [comment]
@Eric Thanks

2018-02-23 0:17 GMT-05:00 Eric Sauer <notifications@github.com>:
