### ISSUE TITLE
Enhancement ideas for post-install validation script

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-toolkit#73]
With #71 , we introduced an initial form of post-install validation for openshift. We also captured some ideas for future enhancements, which I will move to this issue for tracking.

- Fine tune the execution through command line parameters
  - Ability to skip certain tests
  - Set the expected values for certain tests (ie: number of masters)
    - We can look into the addoption functionality. https://docs.pytest.org/en/latest/example/simple.html

**Comment by aizuddin85** [comment]
@etsauer shall we use normal python implementation instead of pytest framework? Any review on the PR I submitted above?
