### ISSUE TITLE
Add node backup helper

### ISSUE THREAD

**Issue by afcollins** [redhat-cop/openshift-toolkit#77]
As an openshift administrator, I want an executable that implements the node backup procedure as documented in the Day2 guide.
https://docs.openshift.com/container-platform/3.11/day_two_guide/environment_backup.html#backing-up-node_environment-backup

"helper" to mean either script or playbook, based on preference.

**Comment by garethahealy** [comment]
@afcollins ; as velero is becoming the de-facto for backups, is still this needed?
