### ISSUE TITLE
Pre-reqs validation script doesn't check for `rhel-7-fast-datapath-rpms` in OCP 3.5

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-toolkit#8]
Per the docs: https://docs.openshift.com/container-platform/3.5/install_config/install/host_preparation.html#host-registration

3.5 added a new channel. we should check for that.

@stratus-ss

**Comment by stratus-ss** [comment]
ok i'll get on this for the week of May 29

**Comment by stratus-ss** [comment]
This issue can be closed @etsauer with the merging of the associated PR
