### ISSUE TITLE
Build UI layer for capacity planner tool

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-toolkit#89]
We would like to build an "executive level" UI around our new capacity planner tool.

Currently the tool traverses an openshift cluster and collects quota, limit, and request data (real time usage data coming soon), and exposes it via a simple API.

The API presents 3 different layers of _scope_:

* Cluster level
  * Total resource allocations for the entire cluster
* Namespace level:
  * Total resources allocation per namespace
* Pod level:
  * same as above for pods

We would like to be able to visualize this information for leadership to give them some assistance in making decisions.

By default, we would want to display the cluster level metrics, but provide the ability to drill down into the namespace and pod. We get a lot of asks to "show be the top 10 largest namespaces" so the ability to sort based on any of the given metrics would be really helpful. Here is a sample of what we should by default for the cluster.

```

Total Cluster Size:
----
	Memory:	151.23707342147827 Gi
	CPU:	37.2 Cores

Amount Claimed By Quota:
----
	Memory:	12.0 Gi (7.934562424755168%)
	CPU:	2 Cores (5.376344086021505%)

Total Limits:
----
	Memory:	108.569046119228 Gi (71.78732281909478%)
	CPU:	11.444999999999997 Cores (30.766129032258053%)

Total Requests:
----
	Memory:	47.17162685096264 Gi (31.190518160518344%)
	CPU:	10.724999999999987 Cores (28.830645161290285%)
```

**Comment by shah-zobair** [comment]
@etsauer I have done something with Grafana dashboard. I can tweak that according to this requirement. Does that help here?

**Comment by etsauer** [comment]
@shah-zobair yes, that would be helpful to see. @raffaelespazzoli mentioned you were working on something for this.

**Comment by garethahealy** [comment]
@etsauer ; is this needed? looking at the PR trail, looks like its solved via:
- https://github.com/redhat-cop/openshift-toolkit/pull/105

**Comment by etsauer** [comment]
I think we can close it.
